name: Auto Release Package

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          npm install
          npm run build
          mv dist my-exoskeleton
          zip -q -r my-exoskeleton.zip my-exoskeleton
          mv my-exoskeleton.zip /tmp/my-exoskeleton.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/my-exoskeleton.zip
          asset_name: my-exoskeleton-${{ github.ref_name }}.zip
          asset_content_type: application/zip
